server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hardware
    username: test
    password: test
    initialization-mode: always
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  artemis:
    user: artemis
    password: simetraehcapa