server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: embedded
  data:
    jpa:
      repositories:
        bootstrap-mode: default
